"""Generate a minimal upstream-native SemRepair adoption skeleton.

The command does not claim adoption.  It creates small, auditable files that a
robotics repository can review and maintain in its own tree.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SUPPORTED_INTEGRATIONS = {
    "native-regression",
    "source-boundary-ci",
    "runtime-refinement",
}


def build_adoption_manifest(
    *,
    repository: str,
    contract_id: str,
    integration_type: str,
    maintained_path: str,
    semantic_layer: str,
) -> dict[str, object]:
    if "/" not in repository:
        raise ValueError("repository must be owner/name")
    if not contract_id:
        raise ValueError("contract_id must be non-empty")
    if integration_type not in SUPPORTED_INTEGRATIONS:
        raise ValueError(
            f"integration_type must be one of {sorted(SUPPORTED_INTEGRATIONS)}"
        )
    if not maintained_path:
        raise ValueError("maintained_path must be non-empty")
    if not semantic_layer:
        raise ValueError("semantic_layer must be non-empty")

    return {
        "schema_version": 1,
        "repository": repository,
        "integration_type": integration_type,
        "semantic_layer": semantic_layer,
        "contract_ids": [contract_id],
        "maintained_path": maintained_path,
        "status": "candidate",
        "claim_boundary": (
            "This manifest records an integration candidate. It becomes external "
            "adoption evidence only when maintained in the named external repository."
        ),
    }


def render_native_regression(contract_id: str) -> str:
    return f'''"""Repository-native semantic regression generated by SemRepair.

Replace the placeholder producer/consumer calls with project-native code.  The
test should preserve the physical semantic relation itself; it does not need to
import SemRepair in permanent upstream CI.
"""

CONTRACT_ID = {contract_id!r}


def test_semantic_contract_regression():
    # TODO: construct a project-native semantic witness.
    # Example patterns:
    # - encode/decode controller round-trip preserves orientation;
    # - recorded executed action equals the command actually sent;
    # - storage repartition preserves episode-local frame lookup;
    # - environment permutation only permutes independent rollouts.
    raise NotImplementedError(
        f"replace this scaffold with a native regression for {{CONTRACT_ID}}"
    )
'''


def render_source_ci() -> str:
    return """name: SemRepair semantic boundary

on:
  pull_request:
  push:

jobs:
  semantic-boundary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install SemRepair release candidate
        run: |
          python -m pip install \
            "git+https://github.com/lindicaphxag-tech/Isaac-GR00T.git@semrepair-v0.3-rc1#subdirectory=semrepair_validation"
      - name: Check semantic boundary
        run: semrepair-source --manifest semrepair.json --json
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a minimal SemRepair upstream-adoption skeleton"
    )
    parser.add_argument("--repository", required=True)
    parser.add_argument("--contract-id", required=True)
    parser.add_argument(
        "--integration-type",
        choices=sorted(SUPPORTED_INTEGRATIONS),
        default="native-regression",
    )
    parser.add_argument("--semantic-layer", required=True)
    parser.add_argument("--maintained-path", default="tests/test_semantic_contract.py")
    parser.add_argument("--output-dir", type=Path, default=Path(".semrepair-adoption"))
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    out = args.output_dir
    if out.exists() and any(out.iterdir()) and not args.force:
        raise SystemExit(
            f"{out} is not empty; use --force or choose another output directory"
        )
    out.mkdir(parents=True, exist_ok=True)

    manifest = build_adoption_manifest(
        repository=args.repository,
        contract_id=args.contract_id,
        integration_type=args.integration_type,
        maintained_path=args.maintained_path,
        semantic_layer=args.semantic_layer,
    )
    (out / "semrepair-adoption.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )

    if args.integration_type == "native-regression":
        (out / "test_semantic_contract.py").write_text(
            render_native_regression(args.contract_id),
            encoding="utf-8",
        )
    elif args.integration_type == "source-boundary-ci":
        (out / "semrepair-source-check.yml").write_text(
            render_source_ci(),
            encoding="utf-8",
        )
        (out / "semrepair.json").write_text(
            json.dumps(
                {
                    "schema_version": 1,
                    "producer": {
                        "path": "path/to/producer.py",
                        "base_type": {"role": "action", "entity": "replace-me"},
                    },
                    "consumer": {
                        "path": "path/to/consumer.py",
                        "base_type": {"role": "action", "entity": "replace-me"},
                    },
                    "rules": [],
                    "adapters": [],
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
    else:
        (out / "RUNTIME_REFINEMENT.md").write_text(
            "# Runtime refinement integration\n\n"
            "Wire the owner-boundary execution/sensor receipt into the semantic "
            "refinement path. Do not relabel requested->executed or stale->fresh "
            "with a pure adapter.\n",
            encoding="utf-8",
        )

    print(out)


if __name__ == "__main__":
    main()
